/**
 * Re-exports genre_artists.json with TypeScript types.
 * genre_artists.json is generated by scripts/generate_curated_tracks.py.
 * After running the script, this file requires no changes.
 */
import genreData from "./genre_artists.json";

export const GENRE_ARTISTS = genreData as Record<
  string,
  Record<string, string[]>
>;

export const GENRE_DISPLAY = {
  rock: "Rock",
  pop: "Pop",
  electronic: "Electronic",
  "hip-hop": "Hip-Hop",
  jazz: "Jazz",
  classical: "Classical",
  folk: "Folk / Country",
} as const;

export const GENRE_KEYS = Object.keys(
  GENRE_DISPLAY,
) as (keyof typeof GENRE_DISPLAY)[];
